spring.application.name=Springsecurity
#spring.security.user.name=vaibhavi
#spring.security.user.password=tandoori
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/User
spring.datasource.username=root
spring.datasource.password=${MY_DB_PASSWORD}